runtime: java17
instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65

env: standard

handlers:
  - url: /.*
    script: this field is required, but ignored
